
// This file has been generated by the GUI designer. Do not modify.
namespace final_project
{
	public partial class DatabaseConnectionDialog
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Label hostLabel;

		private global::Gtk.Label usernameLabel;

		private global::Gtk.Label passwordLabel;

		private global::Gtk.Label databaseLabel;

		private global::Gtk.Label portLabel;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Entry hostEntry;

		private global::Gtk.Entry usernameEntry;

		private global::Gtk.Entry passwordEntry;

		private global::Gtk.Entry databaseEntry;

		private global::Gtk.Entry portEntry;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget final_project.DatabaseConnectionDialog
			this.Name = "final_project.DatabaseConnectionDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child final_project.DatabaseConnectionDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Homogeneous = true;
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hostLabel = new global::Gtk.Label();
			this.hostLabel.Name = "hostLabel";
			this.hostLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Host:");
			this.vbox2.Add(this.hostLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hostLabel]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.usernameLabel = new global::Gtk.Label();
			this.usernameLabel.Name = "usernameLabel";
			this.usernameLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Uživatelské jméno:");
			this.vbox2.Add(this.usernameLabel);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.usernameLabel]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.passwordLabel = new global::Gtk.Label();
			this.passwordLabel.Name = "passwordLabel";
			this.passwordLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Heslo:");
			this.vbox2.Add(this.passwordLabel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.passwordLabel]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.databaseLabel = new global::Gtk.Label();
			this.databaseLabel.Name = "databaseLabel";
			this.databaseLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Databáze:");
			this.vbox2.Add(this.databaseLabel);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.databaseLabel]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.portLabel = new global::Gtk.Label();
			this.portLabel.Name = "portLabel";
			this.portLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Port:");
			this.vbox2.Add(this.portLabel);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.portLabel]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 4;
			w6.Expand = false;
			w6.Fill = false;
			this.hbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Homogeneous = true;
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hostEntry = new global::Gtk.Entry();
			this.hostEntry.CanFocus = true;
			this.hostEntry.Name = "hostEntry";
			this.hostEntry.IsEditable = true;
			this.hostEntry.InvisibleChar = '●';
			this.vbox3.Add(this.hostEntry);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hostEntry]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.usernameEntry = new global::Gtk.Entry();
			this.usernameEntry.CanFocus = true;
			this.usernameEntry.Name = "usernameEntry";
			this.usernameEntry.IsEditable = true;
			this.usernameEntry.InvisibleChar = '●';
			this.vbox3.Add(this.usernameEntry);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.usernameEntry]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.passwordEntry = new global::Gtk.Entry();
			this.passwordEntry.CanFocus = true;
			this.passwordEntry.Name = "passwordEntry";
			this.passwordEntry.IsEditable = true;
			this.passwordEntry.Visibility = false;
			this.passwordEntry.InvisibleChar = '●';
			this.vbox3.Add(this.passwordEntry);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.passwordEntry]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.databaseEntry = new global::Gtk.Entry();
			this.databaseEntry.CanFocus = true;
			this.databaseEntry.Name = "databaseEntry";
			this.databaseEntry.IsEditable = true;
			this.databaseEntry.InvisibleChar = '●';
			this.vbox3.Add(this.databaseEntry);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.databaseEntry]));
			w11.Position = 3;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.portEntry = new global::Gtk.Entry();
			this.portEntry.CanFocus = true;
			this.portEntry.Name = "portEntry";
			this.portEntry.IsEditable = true;
			this.portEntry.InvisibleChar = '●';
			this.vbox3.Add(this.portEntry);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.portEntry]));
			w12.Position = 4;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox1.Add(this.vbox3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
			w13.Position = 1;
			w1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(w1[this.hbox1]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Internal child final_project.DatabaseConnectionDialog.ActionArea
			global::Gtk.HButtonBox w15 = this.ActionArea;
			w15.Name = "dialog1_ActionArea";
			w15.Spacing = 10;
			w15.BorderWidth = ((uint)(5));
			w15.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w15[this.buttonCancel]));
			w16.Expand = false;
			w16.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w15[this.buttonOk]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 244;
			this.Show();
			this.buttonOk.Clicked += new global::System.EventHandler(this.buttonOkClicked);
			this.buttonOk.Pressed += new global::System.EventHandler(this.buttonOkPressed);
		}
	}
}
