
// This file has been generated by the GUI designer. Do not modify.
namespace final_project
{
	public partial class UserDisplay
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView nodeview;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget final_project.UserDisplay
			this.Name = "final_project.UserDisplay";
			this.Title = global::Mono.Unix.Catalog.GetString("Uživatelé");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child final_project.UserDisplay.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeview = new global::Gtk.NodeView();
			this.nodeview.CanFocus = true;
			this.nodeview.Name = "nodeview";
			this.GtkScrolledWindow.Add(this.nodeview);
			this.Add(this.GtkScrolledWindow);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
