
// This file has been generated by the GUI designer. Do not modify.
namespace final_project
{
	public partial class TableForm
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget final_project.TableForm
			this.Name = "final_project.TableForm";
			this.Title = global::Mono.Unix.Catalog.GetString("TableForm");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
