
// This file has been generated by the GUI designer. Do not modify.
namespace final_project
{
	public partial class MenuDesignerWarningDialog
	{
		private global::Gtk.Label messageLabel;

		private global::Gtk.Button buttonFileChoose;

		private global::Gtk.Button buttonContinue;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget final_project.MenuDesignerWarningDialog
			this.Name = "final_project.MenuDesignerWarningDialog";
			this.Title = global::Mono.Unix.Catalog.GetString("Warning");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			// Internal child final_project.MenuDesignerWarningDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.messageLabel = new global::Gtk.Label();
			this.messageLabel.Name = "messageLabel";
			this.messageLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Nebyla nalezena žádná data.");
			this.messageLabel.Wrap = true;
			w1.Add(this.messageLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(w1[this.messageLabel]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Internal child final_project.MenuDesignerWarningDialog.ActionArea
			global::Gtk.HButtonBox w3 = this.ActionArea;
			w3.Name = "dialog1_ActionArea";
			w3.Spacing = 10;
			w3.BorderWidth = ((uint)(5));
			w3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonFileChoose = new global::Gtk.Button();
			this.buttonFileChoose.CanDefault = true;
			this.buttonFileChoose.CanFocus = true;
			this.buttonFileChoose.Name = "buttonFileChoose";
			this.buttonFileChoose.UseUnderline = true;
			this.buttonFileChoose.Label = global::Mono.Unix.Catalog.GetString("_Importovat data");
			this.AddActionWidget(this.buttonFileChoose, 1);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w3[this.buttonFileChoose]));
			w4.Expand = false;
			w4.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonContinue = new global::Gtk.Button();
			this.buttonContinue.CanDefault = true;
			this.buttonContinue.CanFocus = true;
			this.buttonContinue.Name = "buttonContinue";
			this.buttonContinue.UseUnderline = true;
			this.buttonContinue.Label = global::Mono.Unix.Catalog.GetString("_Pokračovat");
			this.AddActionWidget(this.buttonContinue, 2);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w3[this.buttonContinue]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 480;
			this.DefaultHeight = 116;
			this.Show();
			this.buttonFileChoose.Clicked += new global::System.EventHandler(this.OnButtonFileChooseClicked);
			this.buttonContinue.Clicked += new global::System.EventHandler(this.OnButtonContinueClicked);
		}
	}
}
