
// This file has been generated by the GUI designer. Do not modify.
namespace final_project
{
	public partial class MenuDesigner
	{
		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gtk.Notebook notebook1;

		private global::Gtk.HPaned hpaned1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeview;

		private global::Gtk.VButtonBox buttonBox;

		private global::Gtk.Button BtnCategory;

		private global::Gtk.Button button207;

		private global::Gtk.Button button208;

		private global::Gtk.Label pageLabel1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget final_project.MenuDesigner
			this.Name = "final_project.MenuDesigner";
			this.Title = global::Mono.Unix.Catalog.GetString("MenuDesigner");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child final_project.MenuDesigner.Gtk.Container+ContainerChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.hpaned1 = new global::Gtk.HPaned();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 509;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview = new global::Gtk.TreeView();
			this.treeview.CanFocus = true;
			this.treeview.Name = "treeview";
			this.GtkScrolledWindow.Add(this.treeview);
			this.hpaned1.Add(this.GtkScrolledWindow);
			global::Gtk.Paned.PanedChild w3 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.GtkScrolledWindow]));
			w3.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.buttonBox = new global::Gtk.VButtonBox();
			this.buttonBox.Name = "buttonBox";
			this.buttonBox.Homogeneous = true;
			this.buttonBox.Spacing = 2;
			this.buttonBox.BorderWidth = ((uint)(10));
			this.buttonBox.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child buttonBox.Gtk.ButtonBox+ButtonBoxChild
			this.BtnCategory = new global::Gtk.Button();
			this.BtnCategory.CanFocus = true;
			this.BtnCategory.Name = "BtnCategory";
			this.BtnCategory.UseUnderline = true;
			this.BtnCategory.Label = global::Mono.Unix.Catalog.GetString("Vytvořit kategorii");
			this.buttonBox.Add(this.BtnCategory);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.buttonBox[this.BtnCategory]));
			w4.Expand = false;
			w4.Fill = false;
			// Container child buttonBox.Gtk.ButtonBox+ButtonBoxChild
			this.button207 = new global::Gtk.Button();
			this.button207.CanFocus = true;
			this.button207.Name = "button207";
			this.button207.UseUnderline = true;
			this.button207.Label = global::Mono.Unix.Catalog.GetString("Vytvořit podkategorii");
			this.buttonBox.Add(this.button207);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.buttonBox[this.button207]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child buttonBox.Gtk.ButtonBox+ButtonBoxChild
			this.button208 = new global::Gtk.Button();
			this.button208.CanFocus = true;
			this.button208.Name = "button208";
			this.button208.UseUnderline = true;
			this.button208.Label = global::Mono.Unix.Catalog.GetString("Přidat jídlo");
			this.buttonBox.Add(this.button208);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.buttonBox[this.button208]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.hpaned1.Add(this.buttonBox);
			this.notebook1.Add(this.hpaned1);
			// Notebook tab
			this.pageLabel1 = new global::Gtk.Label();
			this.pageLabel1.CanDefault = true;
			this.pageLabel1.Name = "pageLabel1";
			this.pageLabel1.LabelProp = global::Mono.Unix.Catalog.GetString("Návrhář");
			this.notebook1.SetTabLabel(this.hpaned1, this.pageLabel1);
			this.pageLabel1.ShowAll();
			w1.Add(this.notebook1);
			this.scrolledwindow1.Add(w1);
			this.Add(this.scrolledwindow1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 674;
			this.DefaultHeight = 519;
			this.pageLabel1.HasDefault = true;
			this.Show();
			this.BtnCategory.Clicked += new global::System.EventHandler(this.BtnCategoryClicked);
		}
	}
}
