
// This file has been generated by the GUI designer. Do not modify.
namespace final_project
{
	public partial class MenuDesigner
	{
		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gtk.Notebook notebook1;

		private global::Gtk.HPaned hpaned1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView treeview;

		private global::Gtk.VButtonBox buttonBox;

		private global::Gtk.Button BtnCategory;

		private global::Gtk.Button btnSubcategory;

		private global::Gtk.Button btnAddRow;

		private global::Gtk.Button btnDeleteRow;

		private global::Gtk.Label pageLabel1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget final_project.MenuDesigner
			this.Name = "final_project.MenuDesigner";
			this.Title = global::Mono.Unix.Catalog.GetString("MenuDesigner");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child final_project.MenuDesigner.Gtk.Container+ContainerChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.hpaned1 = new global::Gtk.HPaned();
			this.hpaned1.WidthRequest = 100;
			this.hpaned1.CanDefault = true;
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 507;
			this.hpaned1.BorderWidth = ((uint)(5));
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeview = new global::Gtk.TreeView();
			this.treeview.WidthRequest = 200;
			this.treeview.CanFocus = true;
			this.treeview.Name = "treeview";
			this.GtkScrolledWindow1.Add(this.treeview);
			this.hpaned1.Add(this.GtkScrolledWindow1);
			global::Gtk.Paned.PanedChild w3 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.GtkScrolledWindow1]));
			w3.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.buttonBox = new global::Gtk.VButtonBox();
			this.buttonBox.Name = "buttonBox";
			this.buttonBox.Homogeneous = true;
			this.buttonBox.Spacing = 2;
			this.buttonBox.BorderWidth = ((uint)(10));
			this.buttonBox.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child buttonBox.Gtk.ButtonBox+ButtonBoxChild
			this.BtnCategory = new global::Gtk.Button();
			this.BtnCategory.CanFocus = true;
			this.BtnCategory.Name = "BtnCategory";
			this.BtnCategory.UseUnderline = true;
			this.BtnCategory.Label = global::Mono.Unix.Catalog.GetString("Vytvořit kategorii");
			this.buttonBox.Add(this.BtnCategory);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.buttonBox[this.BtnCategory]));
			w4.Expand = false;
			w4.Fill = false;
			// Container child buttonBox.Gtk.ButtonBox+ButtonBoxChild
			this.btnSubcategory = new global::Gtk.Button();
			this.btnSubcategory.CanFocus = true;
			this.btnSubcategory.Name = "btnSubcategory";
			this.btnSubcategory.UseUnderline = true;
			this.btnSubcategory.Label = global::Mono.Unix.Catalog.GetString("Přidat podkategorii");
			this.buttonBox.Add(this.btnSubcategory);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.buttonBox[this.btnSubcategory]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child buttonBox.Gtk.ButtonBox+ButtonBoxChild
			this.btnAddRow = new global::Gtk.Button();
			this.btnAddRow.CanFocus = true;
			this.btnAddRow.Name = "btnAddRow";
			this.btnAddRow.UseUnderline = true;
			this.btnAddRow.Label = global::Mono.Unix.Catalog.GetString("Přidat řádek");
			this.buttonBox.Add(this.btnAddRow);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.buttonBox[this.btnAddRow]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child buttonBox.Gtk.ButtonBox+ButtonBoxChild
			this.btnDeleteRow = new global::Gtk.Button();
			this.btnDeleteRow.CanFocus = true;
			this.btnDeleteRow.Name = "btnDeleteRow";
			this.btnDeleteRow.UseUnderline = true;
			this.btnDeleteRow.Label = global::Mono.Unix.Catalog.GetString("Smazat řádek");
			this.buttonBox.Add(this.btnDeleteRow);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.buttonBox[this.btnDeleteRow]));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			this.hpaned1.Add(this.buttonBox);
			this.notebook1.Add(this.hpaned1);
			global::Gtk.Notebook.NotebookChild w9 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.hpaned1]));
			w9.TabFill = false;
			// Notebook tab
			this.pageLabel1 = new global::Gtk.Label();
			this.pageLabel1.CanDefault = true;
			this.pageLabel1.Name = "pageLabel1";
			this.pageLabel1.LabelProp = global::Mono.Unix.Catalog.GetString("Návrhář");
			this.notebook1.SetTabLabel(this.hpaned1, this.pageLabel1);
			this.pageLabel1.ShowAll();
			w1.Add(this.notebook1);
			this.scrolledwindow1.Add(w1);
			this.Add(this.scrolledwindow1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 674;
			this.DefaultHeight = 519;
			this.pageLabel1.HasDefault = true;
			this.Show();
			this.btnAddRow.Clicked += new global::System.EventHandler(this.OnBtnAddRowClicked);
		}
	}
}
