
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action NovAction;

	private global::Gtk.Action TabulkaAction;

	private global::Gtk.Action NovAction1;

	private global::Gtk.Action TabulkaAction1;

	private global::Gtk.Action UpravitAction;

	private global::Gtk.Action NovAction2;

	private global::Gtk.Action TabulkaAction2;

	private global::Gtk.Action UpravitAction1;

	private global::Gtk.Action newMenuAction1;

	private global::Gtk.Action CategoryAction;

	private global::Gtk.Action addMenuAction;

	private global::Gtk.Action connectionMenuAction;

	private global::Gtk.Action databaseInfoMenuAction;

	private global::Gtk.Action PipojitAction;

	private global::Gtk.VBox vbox3;

	private global::Gtk.HBox hbox2;

	private global::Gtk.MenuBar menubar7;

	private global::Gtk.Statusbar statusbar;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Statusbar statusbar4;

	private global::Gtk.Button BtnStartListening;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.NovAction = new global::Gtk.Action("NovAction", global::Mono.Unix.Catalog.GetString("Nový..."), null, null);
		this.NovAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Nový...");
		w1.Add(this.NovAction, null);
		this.TabulkaAction = new global::Gtk.Action("TabulkaAction", global::Mono.Unix.Catalog.GetString("Tabulka"), null, null);
		this.TabulkaAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Tabulka");
		w1.Add(this.TabulkaAction, null);
		this.NovAction1 = new global::Gtk.Action("NovAction1", global::Mono.Unix.Catalog.GetString("Nový..."), null, null);
		this.NovAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Nový...");
		w1.Add(this.NovAction1, null);
		this.TabulkaAction1 = new global::Gtk.Action("TabulkaAction1", global::Mono.Unix.Catalog.GetString("Tabulka"), null, null);
		this.TabulkaAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Tabulka");
		w1.Add(this.TabulkaAction1, null);
		this.UpravitAction = new global::Gtk.Action("UpravitAction", global::Mono.Unix.Catalog.GetString("Upravit..."), null, null);
		this.UpravitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Upravit...");
		w1.Add(this.UpravitAction, null);
		this.NovAction2 = new global::Gtk.Action("NovAction2", global::Mono.Unix.Catalog.GetString("Nová..."), null, null);
		this.NovAction2.ShortLabel = global::Mono.Unix.Catalog.GetString("Nová...");
		w1.Add(this.NovAction2, null);
		this.TabulkaAction2 = new global::Gtk.Action("TabulkaAction2", global::Mono.Unix.Catalog.GetString("Tabulka"), null, null);
		this.TabulkaAction2.ShortLabel = global::Mono.Unix.Catalog.GetString("Tabulka");
		w1.Add(this.TabulkaAction2, null);
		this.UpravitAction1 = new global::Gtk.Action("UpravitAction1", global::Mono.Unix.Catalog.GetString("Upravit..."), null, null);
		this.UpravitAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Upravit...");
		w1.Add(this.UpravitAction1, null);
		this.newMenuAction1 = new global::Gtk.Action("newMenuAction1", global::Mono.Unix.Catalog.GetString("Nová..."), null, null);
		this.newMenuAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Nový...");
		w1.Add(this.newMenuAction1, null);
		this.CategoryAction = new global::Gtk.Action("CategoryAction", global::Mono.Unix.Catalog.GetString("Kategorie"), null, null);
		this.CategoryAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Tabulka");
		w1.Add(this.CategoryAction, null);
		this.addMenuAction = new global::Gtk.Action("addMenuAction", global::Mono.Unix.Catalog.GetString("Přidat do..."), null, null);
		this.addMenuAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Upravit");
		w1.Add(this.addMenuAction, null);
		this.connectionMenuAction = new global::Gtk.Action("connectionMenuAction", global::Mono.Unix.Catalog.GetString("Připojení k databázi"), null, null);
		this.connectionMenuAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Připojení k databázi");
		w1.Add(this.connectionMenuAction, null);
		this.databaseInfoMenuAction = new global::Gtk.Action("databaseInfoMenuAction", global::Mono.Unix.Catalog.GetString("Informace k připojení"), null, null);
		this.databaseInfoMenuAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Informace k připojení");
		w1.Add(this.databaseInfoMenuAction, null);
		this.PipojitAction = new global::Gtk.Action("PipojitAction", global::Mono.Unix.Catalog.GetString("Připojit"), null, null);
		this.PipojitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Připojit");
		w1.Add(this.PipojitAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar7'><menu name='newMenuAction1' action='newMenuAction1'><menuitem name='CategoryAction' action='CategoryAction'/></menu><menu name='addMenuAction' action='addMenuAction'/><menu name='connectionMenuAction' action='connectionMenuAction'><menuitem name='databaseInfoMenuAction' action='databaseInfoMenuAction'/><menuitem name='PipojitAction' action='PipojitAction'/></menu></menubar></ui>");
		this.menubar7 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar7")));
		this.menubar7.Name = "menubar7";
		this.hbox2.Add(this.menubar7);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.menubar7]));
		w2.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.statusbar = new global::Gtk.Statusbar();
		this.statusbar.Name = "statusbar";
		this.statusbar.Spacing = 6;
		this.hbox2.Add(this.statusbar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.statusbar]));
		w3.Position = 1;
		this.vbox3.Add(this.hbox2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.statusbar4 = new global::Gtk.Statusbar();
		this.statusbar4.Name = "statusbar4";
		this.statusbar4.Spacing = 6;
		this.hbox4.Add(this.statusbar4);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.statusbar4]));
		w5.Position = 0;
		this.vbox3.Add(this.hbox4);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.BtnStartListening = new global::Gtk.Button();
		this.BtnStartListening.CanFocus = true;
		this.BtnStartListening.Name = "BtnStartListening";
		this.BtnStartListening.UseUnderline = true;
		this.BtnStartListening.Label = global::Mono.Unix.Catalog.GetString("Start Listening");
		this.vbox3.Add(this.BtnStartListening);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.BtnStartListening]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.Add(this.vbox3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 777;
		this.DefaultHeight = 499;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.CategoryAction.Activated += new global::System.EventHandler(this.addCategory);
		this.databaseInfoMenuAction.Activated += new global::System.EventHandler(this.databaseConnectionFormAction);
		this.PipojitAction.Activated += new global::System.EventHandler(this.connectToDatabaseAction);
		this.BtnStartListening.Clicked += new global::System.EventHandler(this.BtnStartListeningClicked);
	}
}
